services:
  shortener-redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - shortener-internal
  shortener-mongodb:
    image: mongo:8.2.5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
      MONGO_INITDB_DATABASE: shortener
    volumes:
      - mongodb-data:/data/db
    networks:
      - shortener-internal
volumes:
  redis-data:
  mongodb-data:
networks:
  shortener-internal:
    driver: bridge
